# Generated by Django 4.2.1 on 2023-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/images/default.jpg', upload_to='items/images/%yy/%mm/%d/'),
        ),
    ]
